language: python

matrix:
    include:
        - python: 2.7
          env: CYTHON=''
        - python: 2.7
          env: CYTHON=cython
        - python: 3.5
          env: CYTHON=''
        - python: 3.5
          env: CYTHON=cython
        - python: 3.6
          env: CYTHON=''
        - python: 3.6
          env: CYTHON=cython
        - python: 3.7
          env: CYTHON=''
        - python: 3.7
          env: CYTHON=cython
        - python: 3.8
          env: CYTHON=''
        - python: 3.8
          env: CYTHON=cython

before_install:
    - pip install -U pip
    - pip install numpy>=1.16.5 pysam==0.15.1 $CYTHON

install:
    - python setup.py install

script:
    - pymasc --version
    - pymasc-precalc --version
    - pymasc-plot --version
