name: PyMaSC Tests

on:
  push:
    branches: [ master, modernize-python-support ]
  pull_request:
    branches: [ master ]

jobs:
  test-basic:
    name: Basic Test (Python 3.8, Ubuntu)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy "pysam==0.22.0" "bx-python>=0.10.0"
        pip install scipy matplotlib
        pip install pytest pytest-cov
    
    - name: Build BitArray library
      run: |
        cd external/BitArray
        make clean
        make libbitarr.a
        cd ../..
    
    - name: Build PyMaSC (without Cython)
      run: |
        # Use pre-compiled C sources for Python 3
        python setup.py build_ext --inplace
    
    - name: Run basic tests
      run: |
        python -m pytest tests/unit/test_imports.py -v
    
    - name: Run unit tests
      run: |
        python -m pytest tests/unit/ -v --tb=short
    
    - name: Test PyMaSC command
      run: |
        python -m PyMaSC.pymasc --version